### ISSUE TITLE
Paper reproduce 

### ISSUE THREAD

**Issue by ahhnchangjun** [rvl-lab-utoronto/BFP#3]
Hello, Author

I tried running it with these commands to see if the numbers in the paper were reproduced.
python ./utils/main.py --project bfp --model bfp --dataset seq-cifar100 --buffer_size 500 --alpha_bfp 1 --proj_type 0 --final_feat --pool_dim hw --exp_suffix derpp_fd

I got a performance of CIL = 42.13% and TIL = 84.65, which is different from the numbers in the paper.
I'm using CUDA = 10.2 version, and for TORCH I'm using 1.12.1 version.

Can you help me reproduce the performance ?

Thank you.

**Comment by georgegu1997** [comment]
The command you mentioned runs one of the baselines (but not the main method) in our paper, namely the "FD" variant in Table 2 in the paper. The CIL performance of 42.13% looks quite reasonable (we got 43.81±1.35 in the paper).
